name: Create new dvmvocoder release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref }}

    - name: Build for Windows & Linux
      uses: ./.github/workflows/linux-windows-cmake-build.yml
      with:
        release: true
        release_tag: ${{ github.ref }}
